name: "Feature Request"
description: "Suggest a new feature."
title: "[Feature Request]: "
labels: [ "enhancement" ]
body:
  - type: textarea
    id: issue_description
    attributes:
      label: "Description:"
      description: |
        A concise description of the feature you would like to see in the Gangsta Menu.

        - Include step by step examples of how the feature should work.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots/Video:"
      description: "Attach screenshots or gif/videos to clarify the context. They often convey useful information that is omitted by the description."
    validations:
      required: false