name: "Help"
description: "Ask for a help."
title: "[Help]: "
labels: [ "help wanted" ]
body:
  - type: textarea
    id: issue_description
    attributes:
      label: "Description:"
      description: |
        A concise description of the help you need with the Gangsta Menu.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots/Video:"
      description: "Attach screenshots or gif/videos to clarify the context. They often convey useful information that is omitted by the description."
    validations:
      required: false